default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: namaz_tracker_development

test:
  <<: *default
  database: namaz_tracker_test

production:
  primary: &production_primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *production_primary
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_schema
  queue:
    <<: *production_primary
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_schema
  cache:
    <<: *production_primary
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_schema